apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prometheus-test-demo
  name: prometheus-test-demo
  namespace: {NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-test-demo
  template:
    metadata:
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8998"
        prometheus.io/scheme: http
        prometheus.io/scrape: "true"
      labels:
        app: prometheus-test-demo
    spec:
      containers:
        - image: 172.22.83.19:30003/nju08/prometheus-test-demo:{VERSION}
          name: prometheus-test-demo
          ports:
          - containerPort: 8080
          - containerPort: 8998
          env:
          - name: REDIS_HOST
            value: "redis-service"
          - name: REDIS_PORT
            value: "6379"
          resources:
            requests:
              memory: "128Mi"    
              cpu: "100m"        
            limits:
              memory: "512Mi"    
              cpu: "500m"        
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8998
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8998
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
          - name: REDIS_HOST
            value: "localhost"
          - name: REDIS_PORT
            value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-test-demo
  labels:
    app: prometheus-test-demo
  namespace: {NAMESPACE}
spec:
  type: NodePort
  selector:
    app: prometheus-test-demo
  ports:
    - name: app-port
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: management-port
      protocol: TCP
      port: 8998
      targetPort: 8998
