apiVersion: apps/v1
kind: Deployment
metadata:
  name: yys-app
  labels:
    app: yys-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: yys-app
  template:
    metadata:
      labels:
        app: yys-app
    spec:
      containers:
      - name: yys-app
        image: yys-app:latest
        imagePullPolicy: Always  # 确保总是拉取最新镜像
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "production"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: yys-app-service
  labels:
    app: yys-app
spec:
  selector:
    app: yys-app
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  type: ClusterIP
