apiVersion: v1
kind: Service
metadata:
  name: yunyuansheng3-service
spec:
  selector:
    app: yunyuansheng3
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP # 或者 NodePort, LoadBalancer