apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: yys-app-monitor
  labels:
    app: yys-app
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: yys-app
  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: 30s
    scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
    - default
